In [4]:
import numpy as np

a = np.array([0.2,2.9,4.0])

exp_a = np.exp(a) # 지수함수

print(exp_a)

sum_exp_a = np.sum(exp_a)

print(sum_exp_a)

y = exp_a / sum_exp_a

print("y : ", y)

# 소프트맥스 함수 -> 분류문제를 해결



[ 1.22140276 18.17414537 54.59815003]
73.99369816074747
y :  [0.01650685 0.24561748 0.73787568]


In [8]:
# 개선된 소프트맥스
a = np.array([1010,1000,950])

c = np.max(a)

print(a - c)

print(np.exp(a-c) / np.sum(np.exp(a-c)))

[  0 -10 -60]
[9.99954602e-01 4.53978687e-05 8.75611324e-27]
